version: '3'


services:

  mongo:
    image: 'mongo:latest'
    hostname: 'mongo'
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017'

  gochanges:
    restart: always
    build: .
    environment:
      - MONGO_CONN=mongodb://mongo:27017
    ports:
     - "3822:3822"

volumes:
  mongo_data: